travis:
  secure:
    BINSTAR_TOKEN: 76dV64lx7sNxLex10qguRe4xABec26TlfW3sHdJYrL38hrggffqgkT65UpRACw3nGFNfK7KyLUF7AUqAN+358pc7lwCb/uGZb3C/S6HEdD9fCZOFate7FAAGnua/iI5GVuCjtbe1f2Bo8zFVllDtHn5/d+wNtSgvocZ2e+8oQJ4qMRj2D+YVKnGVqABUPQV6Bf5u4qfbovcaE8yzphgHDCkoCiEJP/IkxCD8zZyv1LKJAJwJ6VXR4uOH5kOCnE0tbZjq7JyC1sqftBpV3+GnA/TzDF9zM4fonUPT/QQR729PuoApYAuwp7BhLubD6j5vz5vOl3Kwgib3CX3DEm0tWyPQq2OWL1oVMqDSLMk7wEVVpptIoseXDmUssKRZVGZbG+b4rRMvojToOD+agtSathyDdYKq4UsGeIOEn/bV/GZZ836bmwrkxIv4kgPuEC2puM5C8Cx2NgCvLalfXXAsx575U69Q9joXPaCst9ImELidzNtwiZsH00viUYK7rGwV0TQbPf5wes5Fe+l8sPJKaKVFuXjav8s4vcQ0vJ7CNS5dmnFjlPd0U76rkH0CCjBRISiZIyGxRDCOFSRv8TMgEXEIoddIeDAb6TqoMuLmtmwmVo5yJ/dA9iMgIQrMlYh367m2NgXsxqr0BhRu/X8r/xo8bg5I7luXIpFOubDU3k4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
